<?xml version="1.0"?>
<robot name="cardboard_box" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:macro name="inertial_cuboid" params="x y z mass">
    <inertia ixx="${(1/12) * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
             iyy="${(1/12) * mass * (x*x + z*z)}" iyz="0.0"
             izz="${(1/12) * mass * (x*x + y*y)}" />
</xacro:macro>

<!-- This is a URDF model of a carboard box with one main body and one AR tag on top -->
<xacro:property name="mass" value="1.0" />
<xacro:property name="lenght" value="0.2" /> <!-- x -->
<xacro:property name="width" value="0.2" /> <!-- y -->
<xacro:property name="height" value="0.2" /> <!-- z -->
<xacro:property name="ground_offset" value="0.1" />
<xacro:property name="scale_factor" value="2.54" />
<xacro:property name="ar_tag_side" value="0.1" />
<!-- margin of the tag border to the box border -->
<xacro:property name="tag_margin" value="0.005" />

  <link name="box_link">
    <inertial>
      <origin xyz="0 0 ${ground_offset}"/>
      <mass value="${mass}" />
        <xacro:inertial_cuboid x="${lenght}" y="${width}" z="${height}" mass="${mass}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${ground_offset}"/>
      <geometry>
        <!-- Mesh linking to cardboard box texture --> 
        <mesh filename="package://sortation_system/media/meshes/cardboard_box.dae" scale="${lenght*scale_factor} ${width*scale_factor} ${height*scale_factor}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${ground_offset+height/2}"/>
      <geometry>
       <box size="${lenght} ${width} ${height}" />
      </geometry>
    </collision>
  </link>

   <joint name="box_to_tag" type="fixed">
     <parent link="box_link"/>
     <child link="ar_tag"/>
     <!-- position origin of joint: at the top of the box -->
     <origin xyz="${lenght/2-ar_tag_side/2-tag_margin} ${width/2-ar_tag_side/2-tag_margin} ${ground_offset+height}"/>
   </joint>

   <link name="ar_tag">
     <visual>
       <geometry>
         <!-- Size of the AR Tag + border, height -->
         <box size="${ar_tag_side} ${ar_tag_side} 0.0001"/>
       </geometry>
       <!-- origin with respect to the position of joint to the box -->
       <origin xyz="0.0 0.0 0.002" rpy="0 0 0"/> <!-- elevate 1 mm -->
     </visual>
   </link>

  <gazebo reference="ar_tag">
      <!-- Set the Tag number -->
      <material>ARTag/0</material>
  </gazebo>

</robot>
